### ISSUE TITLE
Causes crash when parsing response sometimes

### ISSUE THREAD

**Issue by jeff-accountably** [aws-samples/amazon-textract-response-parser#125] opened 2023-03-07 02:56 UTC
https://github.com/aws-samples/amazon-textract-response-parser/blob/70820a416949a01a4e8c9e2a66d6869a4c021579/src-js/src/geometry.ts#L132

add `?.` on dict for both lines fixes it.

```
this._boundingBox = new BoundingBox(dict?.BoundingBox, this);
this._polygon = dict?.Polygon.map((pnt) => new Point(pnt, this));
```

**Comment by athewsey** [comment] 2023-05-11 11:16
I think this is only affecting AnalyzeExpense responses right? In which case we can close it as a duplicate of #102

Otherwise, please let us know what kind of doc/APIs you're seeing the issue on?

**Closed** 2023-08-28 09:15 UTC
Labels: javascript
